development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: barbera_development
  pool: 5
  username: root
  password: password
  host: <%= ENV['DB_HOST'] || 'db' %>
  port: 3306
  socket: ~

production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: barbera_production
  pool: 5
  username: root
  password: password
  host: <%= ENV['DB_HOST'] || 'db' %>
  port: 3306
  socket: ~

