development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: barbera_development
  pool: 5
  username: root
  password: password
  host: 172.19.0.2
  port: 3306
  socket: ~

production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: barbera_production
  pool: 5
  username: root
  password: password
  host: 172.19.0.2
  port: 3306
  socket: ~

